Provide error message when required key constant(s) in `keys.mjs` is missing
w3c/aria-at pull request #608
Opened 2022-01-17 15:38 UTC by howard-e

Address #589.

`npm run build` will now exit when key constant(s) are missing with the message with a suitable error message.

Eg. `ERROR: Key X_AND_SHIFT_XZ found in "tests/checkbox/commands.csv" for "test id 1: navigate to unchecked checkbox" not defined in "tests/resources/keys.mjs".`

2022-01-27 22:42 UTC, mzgoddard requested changes
The call to `addCommandError` is reporting this error already. What do you think about moving this copy into `addCommandError`? Or we can change `addCommandError` in other ways.

2022-02-03 14:41 UTC, howard-e commented
> The call to `addCommandError` is reporting this error already. What do you think about moving this copy into `addCommandError`? 

@mzgoddard I went ahead and used the existing `addCommandError` and moved the copy there as suggested. I changed the copy as such: `[Command]: The key reference "ENTERR" found in "tests/alert/data/commands.csv" for "test id 1: trigger alert" is invalid. Command may not be defined in "tests/resources/keys.mjs".`

To address the issue, the `undefined` return for the keypress object (`{ id: ..., keystroke: ... }`) that happens when the key's definition is missing has been defaulted. This means the script will continue running as expected and report the error afterwards as expected.

2022-02-15 18:57 UTC, alflennik approved these changes
Huge improvement in the readability of the errors, nice. It's true the affected test will not run on the review page, but that seems fine given the fact that a command is broken.

2022-02-16 22:37 UTC, jesdaigle approved these changes

2022-02-17 14:02 UTC, merged